-- 코드를 입력하세요
SELECT ANIMAL_ID,
NAME,
CASE LOCATE('Neutered', SEX_UPON_INTAKE) OR LOCATE('Spayed', SEX_UPON_INTAKE)
    WHEN 1 THEN 'O'
    ELSE 'X'
END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# SELECT * FROM ANIMAL_INS 