-- 코드를 입력하세요
# SELECT MCDP_CD AS 진료과코드, COUNT(MDDR_ID) AS 5월예약건수
# FROM APPOINTMENT 
# GROUP BY MCDP_CD, APNT_YMD
# HAVING DATE_FORMAT(APNT_YMD, '%Y%m') = "202205"
# ORDER BY COUNT(MDDR_ID), 진료과코드;

# SELECT * FROM APPOINTMENT

SELECT MCDP_CD AS 진료과코드, COUNT(MDDR_ID) AS 5월예약건수
FROM APPOINTMENT 
WHERE DATE_FORMAT(APNT_YMD, '%Y%m') = "202205"
GROUP BY MCDP_CD
ORDER BY COUNT(MDDR_ID), 진료과코드;