-- 코드를 입력하세요
SELECT 
a1.TITLE AS TITLE, 
a1.BOARD_ID AS BOARD_ID, 
a2.REPLY_ID AS REPLY_ID, 
a2.WRITER_ID AS WRITER_ID, 
a2.CONTENTS AS CONTENTS, 
DATE_FORMAT(a2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_BOARD a1 JOIN USED_GOODS_REPLY a2 ON a1.BOARD_ID = a2.BOARD_ID 
WHERE 
1=1 
AND a1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY a2.CREATED_DATE, a1.TITLE